### DISCUSSION TITLE
After Update: Bad Request (ImageNotFound)

### DISCUSSION THREAD

**Discussion by Sim0nW0lf** [nicolargo/glances#2007] [Q&A]
After updating Glances I got this error right after launching the contianer:
```
glances       | Traceback (most recent call last):
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
glances       |     response.raise_for_status()
glances       |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
glances       |     raise HTTPError(http_error_msg, response=self)
glances       | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/0ac597fb0bfcd05ee45c15b01091b91ba4b911f882ef1acc6bfe63ca867b4eed/json
glances       |
glances       | During handling of the above exception, another exception occurred:
glances       |
glances       | Traceback (most recent call last):
glances       |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
glances       |     return _run_code(code, main_globals, None,
glances       |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
glances       |     exec(code, run_globals)
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/__main__.py", line 29, in <module>
glances       |     glances.main()
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 150, in main
glances       |     start(config=core.get_config(), args=core.get_args())
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/__init__.py", line 109, in start
glances       |     mode = GlancesMode(config=config, args=args)
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/webserver.py", line 41, in __init__
glances       |     self.stats.update()
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/stats.py", line 230, in update
glances       |     self._plugins[p].update()
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/plugins/glances_plugin.py", line 1158, in wrapper
glances       |     ret = fct(self, *args, **kw)
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/plugins/glances_plugin.py", line 1173, in wrapper
glances       |     ret = fct(*args, **kw)
glances       |   File "/usr/local/lib/python3.9/site-packages/glances/plugins/glances_docker.py", line 250, in update
glances       |     container_stats['Image'] = container.image.tags
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/models/containers.py", line 40, in image
glances       |     return self.client.images.get(image_id.split(':')[1])
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/models/images.py", line 314, in get
glances       |     return self.prepare_model(self.client.api.inspect_image(name))
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
glances       |     return f(self, resource_id, *args, **kwargs)
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/api/image.py", line 251, in inspect_image
glances       |     return self._result(
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
glances       |     self._raise_for_status(response)
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
glances       |     raise create_api_error_from_http_exception(e)
glances       |   File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
glances       |     raise cls(e, response=response, explanation=explanation)
glances       | docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/0ac597fb0bfcd05ee45c15b01091b91ba4b911f882ef1acc6bfe63ca867b4eed/json: Not Found ("no such image: 0ac597fb0bfcd05ee45c15b01091b91ba4b911f882ef1acc6bfe63ca867b4eed: No such image: sha256:0ac597fb0bfcd05ee45c15b01091b91ba4b911f882ef1acc6bfe63ca867b4eed")
```

My docker-compose.yml
```
version: '3.8'

services:
  monitoring:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    pid: host
    privileged: true
    ports:
      - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    runtime: nvidia
    environment:
      - "GLANCES_OPT=-w -6"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances_extern.rule=Host(`monitor.secureserver.de`)"
      - "traefik.http.routers.glances_extern-secure.rule=Host(`monitor.secureserver.de`)"
      - "traefik.http.routers.glances_extern.middlewares=glances_extern-auth"
      - "traefik.http.middlewares.glances_extern-auth.basicauth.users=***************************************************"
      - "traefik.http.routers.glances_extern.entrypoints=http"
      - "traefik.http.middlewares.glances_extern-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.glances_extern.middlewares=glances_extern-https-redirect"
      - "traefik.http.routers.glances_extern-secure.entrypoints=https"
      - "traefik.http.routers.glances_extern-secure.tls=true"
      - "traefik.http.routers.glances_extern-secure.tls.certresolver=http"
      - "traefik.http.routers.glances_extern-secure.service=glances_extern"
      - "traefik.http.services.glances_extern.loadbalancer.server.port=61208"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.glances_extern-secure.middlewares=secHeaders@file,glances_extern-auth"

networks:
  proxy:
    external: true
```

Any idea what to do here?
