### DISCUSSION TITLE
gpus not appearing in glances

### DISCUSSION THREAD

**Discussion by mike37510** [nicolargo/glances#2427] [General]
Hi,

here is the compose docker that I use, but I don't see the GPU information on Glances.
An idea ?

```
version: '3.9'

services:
  
  monitoring:
    container_name : glances
    image: nicolargo/glances:latest-full
    restart: always
    pid: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      - GLANCES_OPT=-w

    # For nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8080:61208

```

I did some prerequisite tests with :

docker run --gpus 'all' --rm ubuntu nvidia-smi

Résult is OK !

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     On   | 00000000:3B:00.0 Off |                  Off |
| 33%   45C    P2    63W / 260W |   1124MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  RTX A6000           On   | 00000000:AF:00.0 Off |                  Off |
| 32%   59C    P2   128W / 300W |  21944MiB / 48685MiB |     90%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
