### DISCUSSION TITLE
Unable to start promtheus exporter in docker

### DISCUSSION THREAD

**Discussion by ackstorm23** [nicolargo/glances#2536] [Q&A]
I can't seem to get glances to start with the prometheus exporter, it throws errors and bails out.

docker-compose.yml
```
services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: always
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /srv/config/docker/glances/config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=US/Central
      - "GLANCES_OPT=--export prometheus -C /glances/conf/glances.conf"
```

glances.conf
```
[prometheus]
host=0.0.0.0
port=9091
#prefix=glances
labels=src:glances
```

errors on startup
```
Attaching to glances
glances  | Can not start Prometheus exporter on None:None (int() argument must be a string, a bytes-like object or a real number, not 'NoneType')
glances exited with code 2
```

Has anyone run into this?  I can't seem to find any issues open or closed for this.
