### DISCUSSION TITLE
Can't get grafana dashboard to load, while everything seems to work fine

### DISCUSSION THREAD

**Discussion by Japhys** [nicolargo/glances#2543] [General]
I have been using Glances for a long time and lately I started using Grafana. Seemed like a good idea to get glances working with Grafana as well. I thought I had everything figured out but somehow I don't get data flowing into my dashboard. Too be honest I was kinda proud of myself to get even this far, I only half know what I am doing haha. Any suggestion I could try? I have noticed my dashboard says host: none.....that kind be right, or?

**Summarize**

Glances -> works
InfluxDB 2 -> works
Glances export to InfluxDB -> works 
InfluxDB glances bucket in Grafana -> at least seems to works -> "datasource is working. 3 buckets found"
But loading the flux dashboard results in empty graphs

I have three seperate composer files I use in Portainer. I already used Grafana en Glances.

**Glances**
```

version: '3'
services:
  glances:
    image: nicolargo/glances:latest
    volumes:
      - /srv/glances:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=--export influxdb2 -C /etc/glances.conf
    ports:
      - 61208:61208
    pid: host
    restart: always
```

**InfluxDB**

```
version: '3'
services:
 influxdb:
   image: influxdb:latest
   container_name: influxdb
   networks:
     - default
   security_opt:
     - no-new-privileges:true
   restart: unless-stopped
   ports:
     - "8086:8086"
   volumes:
     - /srv/influxdb2/config:/etc/influxdb2
     - /srv/influxdb2/db:/var/lib/influxdb2
```

**Grafana**
```
`version: '3.8' 
networks: 
volumes: 
  grafana_data: {} 
services: 
  grafana: 
    image: grafana/grafana:latest 
    user: "1000" 
    container_name: grafana 
    ports: 
      - 3000:3000 
    restart: unless-stopped 
    volumes: 
      - /srv/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources 
      - /srv/grafana:/var/lib/grafana

```

config

```
influxdb2]
host=192.168.1.31
port=8086
protocol=http
org=xxx
bucket=glances
token=xxx
```

Using this file to import
https://raw.githubusercontent.com/nicolargo/glances/master/conf/glances.conf

Influxdb2
![2023-09-03_13-07](https://github.com/nicolargo/glances/assets/24695937/706110a3-5528-4faa-9564-4ff81b125a58)

Grafana
![2023-09-03_12-48](https://github.com/nicolargo/glances/assets/24695937/c77caf20-d5f0-4f5d-9c3f-33b82fd6bc0e)

Grafana dahsboard
![2023-09-03_12-48_1](https://github.com/nicolargo/glances/assets/24695937/94d9dbcb-ada2-4e99-8f07-167c3a53f6a1)
