### DISCUSSION TITLE
Glances Docker ignores configuration file

### DISCUSSION THREAD

**Discussion by auanasgheps** [nicolargo/glances#2646] [General]
**Describe the bug**
I am using a simple configuration file for my Docker instance of Glances:

```
[network]    
hide=docker.,lo,br,veth.*
```
I also tried other simple commands, there's no change.

It used to work perfectly, and Glances log would say: `Read configuration file '/etc/glances.conf'`
This is not happening anymore. I think I was using by mistake an old image, and since I upgraded it, the config file is simply being ignored. There's no mention or error in Glances logs.

This is my docker-compose

version: "2"

```yaml
services:
   monitoring:
    image: nicolargo/glances:latest
    container_name: glances
    privileged: true
    restart: unless-stopped
    pid: host
    volumes:
      - /srv/nvme/docker-apps/glances/logs:/tmp
      - /srv/nvme/docker-apps/glances/conf/glances.conf:/etc/glances.conf
      - /srv/nvme:/mnt/nvme:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"
      - "TZ=Europe/Rome"
    network_mode: "host"
```

 
**To Reproduce**
1. Create a config file for Glances
2. Run Glances with docker using the stack above
3. Config file is ignored

**Expected behavior**
Config file should be applied.

**Screenshots**

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `Debian 11`
 - Glances & psutil versions: `Glances v3.4.0.3`
 - How do you install Glances (Pypi package, script, package manager, source): `Docker Compose`
 - Glances test (only available with Glances 3.1.7 or higher):

 ```
root@nas:~# docker exec -it glances glances --issue
===============================================================================
Glances 3.4.0.3 (/app/glances/__init__.py)
Python 3.11.6 (/venv/bin/python3)
PsUtil 5.9.6 (/venv/lib/python3.11/site-packages/psutil/__init__.py)
===============================================================================
alert         [OK]    0.00003s
[]
amps          [OK]    0.00010s
[]
cloud         [OK]    0.00007s
{}
connections   [OK]    0.07190s
{'ESTABLISHED': 9,
 'LISTEN': 104,
 'SYN_RECV': 0,
 'SYN_SENT': 2,
 'initiated': 2,
 'net_connections_enabled': True,
 'nf_conntrack_count': 242.0,
 'nf_conntrack_enabled': True,
 'nf_conntrack_max': 262144.0,
 'nf_conntrack_percent': 0.092315673828125,
 'terminated': 2}
containers    [OK]    0.00004s
[]
core          [OK]    0.00040s
{'log': 4, 'phys': 4}
cpu           [OK]    0.00024s
{'cpucore': 4,
 'ctx_switches': 5861,
 'guest': 0.0,
 'guest_nice': 0.0,
 'idle': 87.4,
 'interrupts': 4438,
 'iowait': 0.8,
 'irq': 0.0,
 'nice': 0.0,
 'soft_interrupts': 6175,
 'softirq': 1.0,
 'steal': 0.0,
 'syscalls': 0,
 'system': 4.2,
 'time_since_update': 2.109098196029663,
 'total': 26.2,
 'user': 6.6}
diskio        [OK]    0.00040s key=disk_name
[{'disk_name': 'nvme0n1',
  'key': 'disk_name',
  'read_bytes': 1097728,
  'read_count': 41,
  'time_since_update': 2.0875630378723145,
  'write_bytes': 0,
  'write_count': 2}, ...]
folders       [OK]    0.00002s
[]
fs            [OK]    0.00143s key=mnt_point
[{'device_name': '/dev/nvme0n1p1',
  'free': 98549846016,
  'fs_type': 'ext4',
  'key': 'mnt_point',
  'mnt_point': '/tmp',
  'percent': 60.0,
  'size': 246675959808,
  'used': 148109336576}, ...]
gpu           [OK]    0.00002s
[]
help          [OK]    0.00000s
None
ip            [OK]    0.00002s
{}
irq           [OK]    0.00038s key=irq_line
[{'irq_line': 'LOC', 'irq_rate': 2562, 'key': 'irq_line', 'time_since_update': 2.084303140640259}, ...]
load          [OK]    0.00002s
{'cpucore': 4, 'min1': 0.16259765625, 'min15': 0.5576171875, 'min5': 0.322265625}
mem           [OK]    0.00013s
{'active': 3581812736,
 'available': 10305261568,
 'buffers': 443871232,
 'cached': 11006566400,
 'free': 10305261568,
 'inactive': 10993250304,
 'percent': 37.3,
 'shared': 973168640,
 'total': 16433651712,
 'used': 6128390144}
memswap       [OK]    0.00023s
{'free': 4126257152,
 'percent': 3.9,
 'sin': 2326528,
 'sout': 171991040,
 'time_since_update': 2.085275650024414,
 'total': 4294963200,
 'used': 168706048}
network       [OK]    0.00195s key=interface_name
[{'alias': None,
  'cumulative_cx': 14830584,
  'cumulative_rx': 7415292,
  'cumulative_tx': 7415292,
  'cx': 1740,
  'interface_name': 'lo',
  'is_up': True,
  'key': 'interface_name',
  'rx': 870,
  'speed': 0,
  'time_since_update': 2.0790557861328125,
  'tx': 870}, ...]
now           [OK]    0.00001s
'2024-01-05 20:41:55 CET'
percpu        [OK]    0.00003s key=cpu_number
[{'cpu_number': 0,
  'guest': 0.0,
  'guest_nice': 0.0,
  'idle': 44.0,
  'iowait': 0.0,
  'irq': 0.0,
  'key': 'cpu_number',
  'nice': 0.0,
  'softirq': 0.0,
  'steal': 0.0,
  'system': 0.0,
  'total': 56.0,
  'user': 0.0}, ...]
ports         [OK]    0.00022s
[]
processcount  [OK]    0.14156s
{'pid_max': 0, 'running': 1, 'sleeping': 407, 'thread': 1744, 'total': 484}
processlist   [OK]    0.00021s key=pid
[{'cmdline': ['/venv/bin/python3', '-m', 'glances', '--issue'],
  'cpu_percent': 16.1,
  'cpu_times': pcputimes(user=0.45, system=0.33, children_user=0.0, children_system=0.0, iowait=0.0),
  'gids': pgids(real=0, effective=0, saved=0),
  'io_counters': [2596864, 143360, 1499136, 139264, 1],
  'key': 'pid',
  'memory_info': pmem(rss=41459712, vms=52367360, shared=10080256, text=4096, lib=0, data=37523456, dirty=0),
  'memory_percent': 0.2522854489469662,
  'name': 'python3',
  'nice': 0,
  'num_threads': 3,
  'pid': 201390,
  'status': 'R',
  'time_since_update': 2.3337509632110596,
  'username': 'root'}, ...]
psutilversion [OK]    0.00002s
(5, 9, 6)
quicklook     [OK]    0.00033s
{'cpu': 26.2,
 'cpu_hz': 3700000000.0,
 'cpu_hz_current': 3394450000.0000005,
 'cpu_name': 'Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz',
 'mem': 37.3,
 'percpu': [{...}, {...}, {...}, {...}],
 'swap': 3.9}
raid          [OK]    0.00002s
{}
sensors       [OK]    0.00001s key=label
[{'critical': 79,
  'key': 'label',
  'label': 'Composite',
  'type': 'temperature_core',
  'unit': 'C',
  'value': 27,
  'warning': 74}, ...]
smart         [OK]    0.00002s
{}
system        [OK]    0.00000s
{'hostname': 'nas',
 'hr_name': 'Debian GNU/Linux 11 64bit',
 'linux_distro': 'Debian GNU/Linux 11',
 'os_name': 'Linux',
 'os_version': '6.1.0-0.deb11.13-amd64',
 'platform': '64bit'}
uptime        [OK]    0.00011s
{'seconds': 34893}
wifi          [OK]    0.00001s
[]
===============================================================================
Total time to update all stats: 0.22246s
=======================
 ```

**Additional context**
Used to work fine with an old (can't remember) image

**Comment by nicolargo** [comment]
Try to force the /etc/glances.conf file in the GLANCES_OPT variable:

```
services:
   monitoring:
    image: nicolargo/glances:latest
    container_name: glances
    privileged: true
    restart: unless-stopped
    pid: host
    volumes:
      - /srv/nvme/docker-apps/glances/logs:/tmp
      - /srv/nvme/docker-apps/glances/conf/glances.conf:/etc/glances.conf
      - /srv/nvme:/mnt/nvme:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w -C /etc/glances.conf"
      - "TZ=Europe/Rome"
    network_mode: "host"
```
