### DISCUSSION TITLE
Dockerized Web Sever mode with login/password

### DISCUSSION THREAD

**Discussion by Fiallo** [nicolargo/glances#2684] [General]
I don't know if its just me, but when trying to follow the instructions for adding a login and password to my glances web server in a docker compose file I couldn't get it to work for the life of me. I finally figured it out after finding more information through countless google searches. When using the default login "glances" everything worked fine, but setting a custom login caused me issues.

If possible, I believe adding an example on how to implement a login other than the default "glances" in option 1 of the documentation would help others out. 

For anyone that might happen upon this post ill show an example of what I'm talking about. Hopefully my crude explanation is good enough to understand.

Default Login glances:

```
version: '3'

services:
  glances:
    image: nicolargo/glances:latest
    restart: always
    environment:
      - GLANCES_OPT="-w --password"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    secrets:
      - source: glances_password
        target: /root/.config/glances/glances.pwd

secrets:
  glances_password:
    file: ./secrets/glances_password
```
Custom Login:
Add `-u` and `<login>` to your `GLANCES_OPT`.
Change target from `glances.pwd` to `<login>.pwd`
`<login>` will be your custom login name.

```
version: '3'

services:
  glances:
    image: nicolargo/glances:latest
    restart: always
    environment:
      - GLANCES_OPT="-w -u <login> --password"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    secrets:
      - source: glances_password
        target: /root/.config/glances/<login>.pwd

secrets:
  glances_password:
    file: ./secrets/glances_password

```
