### DISCUSSION TITLE
No info about containers resource usage

### DISCUSSION THREAD

**Discussion by the-night-wing** [nicolargo/glances#2723] [Q&A] [answered]
Hello, for some reason containers sections does not show the resource usage per container, disk usage is NaNb, mem is ?, and CPU is 0, any ideas what can be the reason?

![image](https://github.com/nicolargo/glances/assets/45423106/c9dc41c9-d7b2-4b8b-9ea9-314dbd0016d9)

Tasks section works fine:

![image](https://github.com/nicolargo/glances/assets/45423106/c3009a1d-e14d-440c-b647-31c140d2115a)

- System: Alpine Linux 3.13.5 64bit / Linux 6.5.0-1016-aws
- docker: 26.0.0 
- portainer Community Edition 2.19.4

Glances are deployed through docker compose file, the config is below:

```yaml
  glances:
    image: nicolargo/glances:latest-alpine
    # container_name: glances
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.glances.rule: Host(`glances.${DOMAIN?err}`)
      traefik.http.routers.glances.middlewares: admin-secured
      traefik.http.routers.glances.entrypoints: https
      traefik.http.routers.glances.tls.certResolver: 'default'
      traefik.http.services.glances.loadbalancer.server.port: 61208
    environment:
      - "GLANCES_OPT=-w"
    networks:
      - default
```

On another machine it works fine with the same compose config, though OS there on that one is Alpine Linux 3.13.5 64bit / Linux 4.18.0-348.7.1.el8_5.x86_64
