### DISCUSSION TITLE
Help with initial setup please

### DISCUSSION THREAD

**Discussion by Arelius-D** [nicolargo/glances#2785] [Q&A] [answered]
I'm trying to install/run Glances as a container within my `$HOME/docker/glances`

When I try to run `docker compose up` I get following (error)message:

```
[+] Building 0.9s (2/2) FINISHED                                                                docker:default
 => [glances internal] load build definition from dockerfile                                              0.0s
 => => transferring dockerfile: 200B                                                                      0.0s
 => ERROR [glances internal] load metadata for docker.io/library/glances:local-alpine-minimal             0.9s
------
 > [glances internal] load metadata for docker.io/library/glances:local-alpine-minimal:
------
failed to solve: glances:local-alpine-minimal: failed to resolve source metadata for docker.io/library/glances:local-alpine-minimal: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

My `docker-compose.yml`
```
---
services:
  glances:
#  container_name: glances
  image: nicolargo/glances:latest
    build:
      context: ./
      dockerfile: dockerfile
    pid: "host"
    privileged: true
    network_mode: "bridge"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - TZ=Europe/Stockholm
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"
    restart: unless-stopped
```

`ls -al1 $HOME/docker/glances/`
```
total 40
drwxr-xr-x  2 pi pi  4096 May 17 01:59 .
drwxr-xr-x 12 pi pi  4096 May 17 01:52 ..
-rw-r--r--  1 pi pi   525 May 17 02:00 docker-compose.yml
-rw-r--r--  1 pi pi   161 May 17 02:01 dockerfile
-rw-r--r--  1 pi pi 23759 May 17 02:01 glances.conf
```

**All and any input on how sort this and actually pull and run the tool would be much appreciated!**

To the developers of Glances and it's documentation.. _please don't get offended I don't mean to be rude.. but_ the documentation should have a section touching installation using `docker-compose` and that should be influenced of how that process generally works..

**Comment by RazCrimson** [comment]
Uh, could you just tell me why you have the `image` entry commented in your compose file?

Just uncommenting it and commenting the `build` section should work as long as you are not in some unsupported architecture.

**Reply by Arelius-D** [reply]
Oh that's a typo sorry, I'll edit the post and fix it but I don't have it hashed in my actual docker-compose.yml though.

**Comment by RazCrimson** [comment, marked as answer]
Also this page should have some compose examples:
https://glances.readthedocs.io/en/latest/docker.html

Please use the `latest` tag for docker images. `latest-alpine` is deprecated

**Reply by Arelius-D** [reply]
Thank you, I'll read that(!), try again as soon as possible and report back!

**Reply by Arelius-D** [reply]
Ok, managed to pull the image and run using:
```
---
services:
  monitoring:
    container_name: glances
    image: nicolargo/glances:latest-full
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=-w"
      - TZ=Europe/Stockholm
    restart: unless-stopped
```
![image](https://github.com/nicolargo/glances/assets/168124713/bb903f7c-1780-4b49-8898-b1450a0d8a36)

**Question**
- why can I not reach the WebUI with `network_mode: bridge`?
- ..and is it normal or common to get these errors I'm getting?

**Reply by RazCrimson** [reply]
> why can I not reach the WebUI with network_mode: bridge?

If you use bridge network mode, you need to forward ports. Technical explanation would require diving into how docker works with NAT.

Try using something like this and you should be able to access it.
```
services:
  monitoring:
    container_name: glances
    image: nicolargo/glances:latest-full
    pid: host
    ports:
     - 61208: 61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=-w"
      - TZ=Europe/Stockholm
    restart: unless-stopped
 ```

> ..and is it normal or common to get these errors I'm getting?

Depends on your system. Its fine to have spikes as long as ur doing some thing heavy on the system. 

Glances on a RPi is not light by any means, I would recommend using the `latest` tag unless you are interested in all the plugin offered in the full image. Otherwise determine the plugin you want to use and disable the other plugins.
