### DISCUSSION TITLE
Docker - Custom username + password not asked upon loading the website

### DISCUSSION THREAD

**Discussion by EpicLPer** [nicolargo/glances#2816] [Q&A]
Heya,

I'm a bit lost right now, I've tried a bunch of things but I'm definitely missing (probably a small and tiny) thing somewhere ^^" I want to access Glances over the internet and behind a Proxy + IP restriction but I'm trying to secure it a bit further.

**tl;dr** - I've set up a Docker, created a password file and if I leave everything at `glances.pwd` it works. However using something like `glances_customusername.pwd` doesn't ask for a password anymore.

I'm trying to run Glances in a Docker and want to password protect it, so far I've set everything up as it probably should be. My Docker config looks as following:
```yaml
version: '3.9'
services:
  glances:
    image: nicolargo/glances
    restart: always
    pid: "host"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - TZ=${TZ}
      - "GLANCES_OPT=-C /glances/conf/glances.conf -u glances_customusername --password -w"
    secrets:
      - source: glances_customusername
        target: /root/.config/glances/glances_customusername.pwd

secrets:
  glances_customusername:
    file: ./glances_customusername.pwd

networks:
  default:
    external:
      name: my_bridge
```

I also created a `glances_customusername.pwd` and `glances.config` file in the same directory as the docker compose file. The container starts up just fine as it should, it also prints the URL and I can access it, however **it doesn't ask for a username and password**.

The only way I got this to work so far is by using the default `glances.pwd` instead of a custom username, that way I get asked for a username and password. But if possible I'd want to change the username too, just for that extra added protection layer on top :)

Thanks already for your help!
