### DISCUSSION TITLE
Basic question, adding docker support

### DISCUSSION THREAD

**Discussion by Aetherinox** [nicolargo/glances#2858] [Q&A]
I've looked through the Github repo, and the ReadTheDocs, and while it does explain how to enable GPU for docker, I see no mention at all of enabling the `docker` plugin on the Glances docker image. I've been high and low over many sites.

I've mounted the docker sock, I've made sure the glances.conf has
```conf
[containers]
disable=False
```

But no matter what I've done, I see no definite way to enable this so that it lists all of my docker containers.

Running `-w` web version. Also made sure to use the image `latest-full` and even tried `--enable-plugin docker` and `containers` in docker-compose.yml

Help appreciated.

**Comment by nicolargo** [comment]
Hi @Aetherinox 

there is nothing to do to enable the Docker plugin in Glances Docker image.

The only things to do is to mount the Docker (and Podman if you use it) sockets thanks to "-v /var/run/docker.sock:/var/run/docker.sock:ro -v /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro"

On my system (Ubuntu 24.04), if i ran:

```
docker run -p 61208-61209:61208-61209 -it -e TZ="${TZ}" -e GLANCES_OPT="" -v /var/run/docker.sock:/var/run/docker.sock:ro -v /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro --pid host nicolargo/glances:latest
```

i got:

![image](https://github.com/nicolargo/glances/assets/776747/f65f46e3-0a82-43ee-acc5-03eaa0de1e8f)

**Comment by Aetherinox** [comment]
Interesting.
That's the current issue I'm at, is I've done the above, and yet no docker containers appear

```yml
  glances:
    container_name: ${W_GLANCES_DOCK_CONTAINER_NAME}
    image: ${W_GLANCES_DOCK_IMAGE}:${W_GLANCES_DOCK_TAG}
    restart: unless-stopped
    pid: host
    env_file:
      - ./.env
    environment:
      TZ: ${SERVER_TIMEZONE}
      GLANCES_OPT: -C /glances/conf/glances.conf --webserver --enable-plugin containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      # - /etc/os-release:/etc/os-release:ro
      - ./glances/glances.conf:/glances/conf/glances.conf
```

And I get just a list of the processes, and the items on the side.

I've tried with, and without ` - /etc/os-release:/etc/os-release:ro`
