### ISSUE TITLE
Docker image for arm?

### ISSUE THREAD

**Issue by AnderssonPeter** [nicolargo/glances#1135]
Im using docker on a raspberry pi 3, any chance there is a docker image for arm32v6 or arm32v7?

**Comment by uSpike** [comment]
It may be a lot easier to simply use the `multiarch/ubuntu-debootstrap` images already available.  You can run them on your x86 machine because they include static qemu binaries.

AFACT, it should be as simple as changing the `FROM ubuntu` line to `FROM multiarch/ubuntu-debootstrap:armhf-xenial` and making sure you have binutils set up on your host, or just run

```
$ docker run --rm --privileged multiarch/qemu-user-static:register
```

**Comment by jrbenito** [comment]
@nicolargo ,

How do you build X86 docker images?  More specifically, do you use a CI? I check the .travis.yml and it seems not, hence you might be doing it somehow manually...

Thanks

**Comment by nicolargo** [comment]
@jrbenito Done automatically  by hub.docker.com every time i push something on the develop or master branch.

**Comment by MrAdam** [comment]
If you want to use it as part of your docker-compose.yml, you can do the following so it's pulled directly from the repository and compiled on your ARM-machine, ensuring it works on your platform:
```
services:
  glances:
    build: https://github.com/nicolargo/glances.git#develop:/docker-files/devel-arm/
    restart: always
    ports:
      - 61208:61208
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
```
