### ISSUE TITLE
Docker plugin WebUI is broken in the latest DEVELOP branch

### ISSUE THREAD

**Issue by bounty1342** [nicolargo/glances#1174]
#### Description
Update the the "nicolargo/glances:latest"

#### Versions
* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

#### Logs
Failed to connect to bus: No such file or directory

The issue is not present on the "nicolargo/glances:stable"

**Comment by nicolargo** [comment]
What is your Docker version ?

As said in the [release note](https://github.com/nicolargo/glances/blob/develop/NEWS#L23): Support for Docker API < 2.0 is deprecated (Docker plugins)

**Comment by nicolargo** [comment]
Forget my last comment. Also reproduced on my side. It came from the default glances.conf file where the systemd AMP is enable. I just commit a new version with all AMP plugins disable by default.

Wait the generation of the Glances's Docker image and please test it.

**Comment by bounty1342** [comment]
Hi @nicolargo, I got the following error :

`Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe`


# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:24 2017
 OS/Arch:      linux/amd64
 Experimental: false

Let me know if I can provide more info, or help in any ways.

**Comment by nicolargo** [comment]
Can not reproduce on my PC:

    # docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -it docker.io/nicolargo/glances

With 4 running containers (+ Glances container):

```
 # docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
b842a667ecd7        jupyterhub/jupyterhub    "jupyterhub"             10 minutes ago      Up 10 minutes       8000/tcp                                                                 jupyterhub
a0c4b176712c        grafana/grafana:latest   "/run.sh"                8 hours ago         Up 8 hours          0.0.0.0:3000->3000/tcp                                                   grafana
b14d1d495ecb        telegraf:latest          "/entrypoint.sh te..."   8 hours ago         Up 8 hours          8092/udp, 8125/udp, 8094/tcp                                             telegraf
abbd15ef55d6        influxdb:latest          "/entrypoint.sh in..."   8 hours ago         Up 8 hours          0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp, 0.0.0.0:8090->8090/tcp   influxdb
```

Give me :

![selection_344](https://user-images.githubusercontent.com/776747/32008608-ed1a7056-b9ac-11e7-9203-0a3a2340a67f.png)

**Comment by bounty1342** [comment]
```yaml
version: '2'
services:  
    glances:
        image: nicolargo/glances:**stable**
        container_name: glances
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        pid: "host"
        ports:
            - 61208:61208
            - 61209:61209
        environment:
            - GLANCES_OPT=-w
        labels:
            - "traefik.frontend.rule=Host:glances.${DNS_USER}.${DNS}"
            - "traefik.port=61208"
            - "traefik.backend=glances"
            - "traefik.backend.loadbalancer.method=wrr"
            - "traefik.frontend.entryPoints=http,https" 
        restart: always
```
![image](https://user-images.githubusercontent.com/6307253/32013284-e16841b2-b9ba-11e7-844b-5f9af2b67877.png)

I ran the following commands :
```console
docker-compose stop glances
docker-compose rm glances
docker-compose up glances
```
```yaml
version: '2'
services:  
    glances:
        image: nicolargo/glances:**latest**
        container_name: glances
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        pid: "host"
        ports:
            - 61208:61208
            - 61209:61209
        environment:
            - GLANCES_OPT=-w
        labels:
            - "traefik.frontend.rule=Host:glances.${DNS_USER}.${DNS}"
            - "traefik.port=61208"
            - "traefik.backend=glances"
            - "traefik.backend.loadbalancer.method=wrr"
            - "traefik.frontend.entryPoints=http,https" 
        restart: always
```
![image](https://user-images.githubusercontent.com/6307253/32013574-d1e9d326-b9bb-11e7-9a9a-5c6d6b898164.png)

The docker plugin vanished. 
Maybe is just hidden by default ? Is there a shortcut to enable it ?
