### ISSUE TITLE
apparmor="DENIED" operation="ptrace" profile="docker-default"

### ISSUE THREAD

**Issue by juan11perez** [nicolargo/glances#1266]
* Glances (glances -V): docker latest image
* Operating System (lsb_release -a): Ubuntu Server 18.04LTS

When running the docker in --export influxdb mode. The syslog is continuously spammed with the following error:

May 20 18:09:58 home kernel: [ 8661.017018] audit: type=1400 audit(1526825398.119:8268): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=5868 comm="python" requested_mask="trace" denied_mask="trace" peer="unconfined"

stopping the container produces this: 

May 20 18:09:59 home dockerd[910]: time="2018-05-20T18:09:59+04:00" level=info msg="shim reaped" id=2de8ef8e38980a1d719368afdfec772fbe5271c5479fb85a588edca8241c58eb module="containerd/tasks"
May 20 18:09:59 home dockerd[910]: time="2018-05-20T18:09:59.528143448+04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 20 18:09:59 home systemd-networkd[798]: veth03f600a: Lost carrier
May 20 18:09:59 home kernel: [ 8662.713286] br-3b7a79e60370: port 6(veth03f600a) entered disabled state
May 20 18:09:59 home systemd-udevd[23675]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 20 18:09:59 home networkd-dispatcher[962]: WARNING:Unknown index 34 seen, reloading interface list
May 20 18:09:59 home kernel: [ 8662.779878] device veth03f600a left promiscuous mode
May 20 18:09:59 home kernel: [ 8662.779886] br-3b7a79e60370: port 6(veth03f600a) entered disabled state

No further errors are logged.
The behaviour is replicated in the docker stable image.

**Comment by nicolargo** [comment]
Hi @juan11perez 

not reproduced on my laptop (Docker version 17.05.0-ce, build 89658be).

What is your Docker engine version ?

**Comment by juan11perez** [comment]
Good day @nicolargo
Docker version 18.03.1-ce, build 9ee9f40

**Comment by attzonko** [comment]
I know this is more than a year later, but I stumbled on this issue as I was seeing it as well. Changing the option, resolved the problem for me. I would say you can close the issue :)

**Comment by gnana03** [comment]
@attzonko  can u pls let me know how u have added --security-opt apparmor=unconfined' to your docker command line ? i am very new to docker and all these.
Thanks in advance!

**Comment by attzonko** [comment]
@gnana03 Here is the command line I use for my container:
```
docker run -d --security-opt apparmor=unconfined --name glances --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances
```

**Comment by tyzen9** [comment]
Here is my docker-compose configuration to enable apparmor=unconfirmed.  I know this is an old post, but it helped me years later come up with this, and maybe it can help someone else.  I use the following to launch a glances instance cleanly as a Portainer stack.

```yaml
services:
  glances:
    image: nicolargo/glances:latest
    restart: always
    pid: host
    network_mode: host
    security_opt:
      - apparmor=unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
      # This allows for a custom glances.conf file on the docker host server
      - /config/glances/glances.conf:/etc/glances.conf
    environment:
      - "GLANCES_OPT=-w"
```
