### ISSUE TITLE
Add a docker-compose example

### ISSUE THREAD

**Issue by rgarrigue** [nicolargo/glances#1334]
Hi

Maybe you should add a docker-compose example running glances, either a file or in the doc, to get started straight away ? 

Here's an example with traefik as a reverse proxy, a simple whoami, both of them to make it more realistic, and finaly glances. 

```
version: '3'

services:
  reverse-proxy:
    image: traefik:alpine
    command: --api --docker
    ports:
      - "80:80"     
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

  monitoring:
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: host
    volumes:    
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    labels:      
      - "traefik.port=61208"      
      - "traefik.frontend.rule=Host:glances.docker.localhost"
      
```

And thanks a lot for glances, I've been using it for ages now, one of my best tools

**Comment by nicolargo** [comment]
I discover Traefik with your message. Nice peace of code.

Can you propose a pull request on the DEVELOP branch with this example (or others) in the documentations (/docs).

Thanks !

**Comment by nicolargo** [comment]
Done

**Comment by chuong98** [comment]
@nicolargo Is there anyway that I can use PathPrefix with Traefik, for example:
This is my docker compose:
```
  server-monitor:
    image: nicolargo/glances:3.3.0.2-full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/glances.conf:/etc/glances.conf
    environment:
      - "GLANCES_OPT=-w -C /etc/glances.conf"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility
    deploy:
      labels:
        - traefik.enable=true
        # router
        - traefik.http.routers.server-monitor.rule=PathPrefix(`/server-monitor`)
        - traefik.http.routers.server-monitor.entrypoints=web
        #service
        - traefik.http.services.server-monitor.loadbalancer.server.port=61208
```
