### ISSUE TITLE
How to run glances in docker and get CPU/RAM/Process of the host machine?

### ISSUE THREAD

**Issue by chetankabra** [nicolargo/glances#1350]
#### Description
I have used below configuration, to run glances in my docker-compose.yaml, but I am not able to get
the CPU/RAM and other details from the glances about the host machine. 
glances are displaying me ram docker containers allocated ram and other details?

 glances:
    image:  nicolargo/glances
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/glances.conf:/glances/conf/glances.conf
    environment:
      - GLANCES_OPT= -C conf/glances.conf
    pid: "host"
    privileged: true

#### Versions

* Glances & psutil (glances -V):Glances v3.1.0_beta 
* Operating System (lsb_release -a):  psutil v5.4.3

**Comment by PaulReiber** [comment]
This isn't an issue with glances - that's how docker is supposed to work.  The whole idea with containment is that the container is limited to only seeing the resources it's allowed to see.  

The only way to get to resources "on the host machine" is to expose those resources to the container in your docker config.

**Comment by hajo62** [comment]
> The only way to get to resources "on the host machine" is to expose those resources to the container in your docker config.

You might want to give some examples?

**Comment by warsix4** [comment]
I would like to know how this is done as well.

**Comment by geertmeersman** [comment]
This is how I run it
```
  glances:
    image: nicolargo/glances:latest-alpine
    container_name: glances
    restart: always
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /docker/volumes/glances/config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Brussels
      - "GLANCES_OPT=-w"
    ports:
      - 61208-61209:61208-61209

```
