### ISSUE TITLE
Update the Snap package

### ISSUE THREAD

**Issue by NatoBoram** [nicolargo/glances#1353]
#### Description

I have installed the snap package of Glances using the workaround at #1310 and it works beautifully, except it recently started to nag me about updating it. However, there are no updates available for me.

```yaml
name:      glances
summary:   Glances an Eye on your system. A top/htop alternative.
publisher: Nicolargo
license:   unset
description: |
  Glances is a cross-platform monitoring tool which aims to present
  a maximum of information in a minimum of space through a curses or
  Web based interface. It can adapt dynamically the displayed information
  depending on the user interface size.
commands:
  - glances
snap-id:      1EoDZZlSxxJ3YD0gyt6mIRh1fIFE71MM
tracking:     stable
refresh-date: today at 03:15 UTC
channels:                    
  stable:    2.11.1 (5) 10MB -
  candidate: 2.11.1 (5) 10MB -
  beta:      2.11.1 (5) 10MB -
  edge:      2.11.1 (5) 10MB -
installed:   2.11.1 (5) 10MB -
```

#### Versions

* Glances v2.11.1 with psutil v5.4.2

```yaml
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

#### Logs

```log
You are using Glances version 2.11.1, however version 3.0.2 is available.
You should consider upgrading using: pip install --upgrade glances
```
