### ISSUE TITLE
How to use GPU stats under a docker container?

### ISSUE THREAD

**Issue by oleksandrlazariev** [nicolargo/glances#1375]
Hi! I could not find how to enable GPU monitoring when Glances is running under a docker container using the official docker image and the `docker run -d --name glances --restart="always" -p 61208-61209:61208-61209 -e GLANCES_OPT="-w" -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances`
I've also entered into the running container to check if `nvidia-ml-py3` installed, and it is. 
Is it possible to monitor GPU stats in this way at all? What should I do if yes?

**Comment by nicolargo** [comment]
Never tested it inside a container... Perhaps you should have a look on the official **nvidia-ml-py**  lib and check how the stats are grabbed from the system.

**Comment by bradcornford** [comment]
I've just tackled this myself, using docker compose and nvidia-container-runtime (https://github.com/NVIDIA/nvidia-container-runtime), i used the following: 

`
version: "2.3"

services:
  glances:
    image: nicolargo/glances
    container_name: glances
    pid: host
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - GLANCES_OPT=-w -6
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
`

**Comment by rubens-curious** [comment]
Didnt work for me, here is, is think, a more complete answer : 
There is two missing dependencies for it to work (atleast for nvidia gpu).

Here is the Dockerfile : 
`
FROM nicolargo/glances
RUN pip install py3nvml
RUN pip install nvidia-ml-py3
CMD python3 -m glances -C /etc/glances.conf $GLANCES_OPT
`

Which I put in a folder named "glances" right next to the docker-compose.yml file.

Here is the docker-compose service : 
`
version: '3.8'

services:
 glances:
    build: "./glances"
    container_name: "glances"
    pid: host
    privileged: true
    runtime: nvidia
    environment:
        - GLANCES_OPT=-w
        - NVIDIA_VISIBLE_DEVICES=all
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
    network_mode: host
    restart: always
`

**Comment by RazCrimson** [comment]
@landcraft 
Intel GPUs are not supported by Glances 
Issue for support tracked here: https://github.com/nicolargo/glances/issues/994

**Comment by RazCrimson** [comment]
To use nvidia GPU with Docker 19.03 and above, you can use the following option:
`docker run -it --gpus all [OPTIONS] nicolargo/glances:latest-full`

For Docker Compose, here is an example:
```
version: '3.8'

services:
  monitoring:
    image: nicolargo/glances:latest-full
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    # For nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
Reference: https://docs.docker.com/compose/gpu-support/
