### ISSUE TITLE
Password for Web/Browser mode

### ISSUE THREAD

**Issue by GomoDD** [nicolargo/glances#1674]
#### Description

I read the manual few times and cannot seem to get my Glances (which is running in web mode) password protected.  Would be awesome if you could provide syntax example or show exactly which part of the config needs to be modified & how. 

I'm not the only one having this issue / wondering how to get it to work. See links below:
https://urlshort.host/glances1
https://urlshort.host/glances2

#### Versions
Glances v3.1.4.1 
Ubuntu 18.04 64bit

Please update the documentation! Thanks!

**Comment by nicolargo** [comment]
Hi,

First time, run Glances with:

```
glances --username --password -w
Define the Glances webserver username: foo
Define the Glances webserver password (foo username): bar
Password (confirm): bar
Do you want to save the password? [Yes/No]: Yes
```
It will ask you a username and a password.

Others times, run Glances with:

`glances -u foo -w`

If you want to reset the foo password:

`rm ~/glances/config/foo.pwd`

**Comment by Yohan9206** [comment]
> Hi,
> 
> First time, run Glances with:
> 
> ```
> glances --username --password -w
> Define the Glances webserver username: foo
> Define the Glances webserver password (foo username): bar
> Password (confirm): bar
> Do you want to save the password? [Yes/No]: Yes
> ```
> 
> It will ask you a username and a password.
> 
> Others times, run Glances with:
> 
> `glances -u foo -w`
> 
> If you want to reset the foo password:
> 
> `rm ~/glances/config/foo.pwd`

Hi,
Where to add this settings to my .yml file?
Kind Regards,
Yohan

**Comment by hadim** [comment]
Same issue here, I must use auth to be able to run glances on my docker setup:

```yaml
  glances:
    container_name: glances
    image: nicolargo/glances
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /MY/PATH/Glances/glances.conf:/glances/conf/glances.conf
    environment:
      - GLANCES_OPT=-w --username myuser --password test
    restart: unless-stopped
```

Error message is `glances: error: unrecognized arguments:`. Looks like the docker image has not been updated for a while now.

xref with https://discourse.linuxserver.io/t/request-glances/1857
