### ISSUE TITLE
Alpine Image is broken

### ISSUE THREAD

**Issue by auanasgheps** [nicolargo/glances#1720]
#### Description

Hi, today watchtower updated my glances alpine container and since then it's broken.

All the log from Potainer says is

`/bin/sh: python: not found
`
Whis is printed every second or so. The container is constantly rebooted.

I've switched to the non-apline image and works fine. 
Here's my config below

```
version: "2"

services:
   monitoring:
    image: nicolargo/glances:latest-alpine
    container_name: glances
    privileged: true
    restart: unless-stopped
    pid: host
    volumes:
      - /srv/dev-disk-by-label-nvme/docker-apps/glances/conf:/glances/conf
      - /srv/dev-disk-by-label-nvme/docker-apps/glances/logs:/tmp
      - /srv/dev-disk-by-label-nvme:/mnt/nvme:ro
      - /srv/dev-disk-by-label-HDD2:/mnt/HDD2:ro
      - /srv/dev-disk-by-label-HDD3:/mnt/HDD3:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "GLANCES_OPT=-w"
    ports:
        - "61208-61209:61208-61209"
networks:
    default:
        external: 
            name: mynet

```
The container restarts continuosly outputting the python bug.

#### Versions

* Glances & psutil (glances -V): can't do this
* Operating System (lsb_release -a): Debian 10 - OpenMediaVault 5

#### Logs
I can't get more logs.
