### ISSUE TITLE
docker image glances-  cpu cores shows only 4 cores

### ISSUE THREAD

**Issue by vajonam** [nicolargo/glances#1761]
#### Description

![image](https://user-images.githubusercontent.com/152501/99891685-a56c5e00-2c3a-11eb-851a-1520adb9a6d6.png)

interesting running on bare metal only shows 4 cores, I have 2x4core CPUs , so should show 8 cores. 

#### Versions

```
    glances_server:
        image: nicolargo/glances
        container_name: glances_server
        privileged: true
        environment: 
            - GLANCES_OPT=-w 
            - NVIDIA_VISIBLE_DEVICES=all 
            - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
        volumes:
            - /opt/docker/configs/glances/glances.conf:/glances/conf/glances.conf
            - /var/run/docker.sock:/var/run/docker.sock:ro 
        pid: host
        restart: always
        privileged: true
        ports: 
            - 61208:61208

```
#### Logs

https://pastebin.com/QiVkLRZ6
