### ISSUE TITLE
Docker not running on arm

### ISSUE THREAD

**Issue by hackmonker** [nicolargo/glances#1914]
**Describe the bug**

When I try to run the docker on Rpi 4, it does not run giving an error

```/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed```

**To Reproduce**
1. Start Glances docker using compose
2. does not start
3. See error in logs

**Desktop (please complete the following information):**
 - OS: Debian

- Logs:

```/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed
/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed
/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed
/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed
/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed
/usr/local/bin/python3: No module named glances.__main__; 'glances' is a package and cannot be directly executed
```

Compose File:

```
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    environment:
      TZ: ${TZ}
      UID: ${PUID}
      GID: ${PUID}
      GLANCES_OPT: "-w"
    ports:
      - 61208:61208
    volumes:
      - ${DOCKERCONFDIR}/glances/conf:/glances/conf:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    restart: unless-stopped
```
