### ISSUE TITLE
Container uptime wrong (timezone bug?)

### ISSUE THREAD

**Issue by golles** [nicolargo/glances#2059]
**Describe the bug**
I've rebooted the host machine recently and noticed that container uptimes are 2 hours more than the machine uptime. 
My assumption is that this has to do with my local timezone being 2 hours ahead of GMT.

**To Reproduce**
```yaml
  glances:
    container_name: glances
    restart: unless-stopped
    image: nicolargo/glances:latest-full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}/glances:/etc/glances
    ports:
      - 61208:61208
    pid: host
    privileged: true
    environment:
      - GLANCES_OPT=-w
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
```

**Expected behavior**
Container uptime couldn't be longer than the machine uptime

**Screenshots**
<img width="1236" alt="Schermafbeelding 2022-05-29 om 20 52 05" src="https://user-images.githubusercontent.com/2211503/170887160-df3111b9-8e79-4667-bd69-88433606825b.png">

**Desktop (please complete the following information):**
N/A

**Additional context**
If more info is required, let me know
