### ISSUE TITLE
docker-compose and password secrets not working

### ISSUE THREAD

**Issue by yed01** [nicolargo/glances#2107]
Hi,
I have a problem with password authentication and Docker.
I created a password file an now trying to get it to work with Docker, but it fails with the error message "services.glances.secrets.0.mode must be a number".
I'm sure there is something wrong in my docker-compose file, I used the instructions here: [https://github.com/nicolargo/glances/pull/1781/commits/3cca1d7982093d9652d15c40eac693c9ee7fa19c](https://github.com/nicolargo/glances/pull/1781/commits/3cca1d7982093d9652d15c40eac693c9ee7fa19c)

``` 
version: "3.8"
services:
  glances:
    image: nicolargo/glances:latest
    secrets:
      - source: glances_password
        target: /root/.config/glances/glances.pwd
        mode: '0440'
    container_name: Glances
    restart: always
    ports:
      - "61208:61208"
    environment:
      GLANCES_OPT: "-C /etc/glances.conf -w"
     volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/yed/docker/glances/glances.conf:/etc/glances.conf"
    pid: "host"

secrets:
  glances_password:
    file: /home/yed/docker/glances/yed.pwd 
```

Any help would be appreciated.
