### ISSUE TITLE
Wrong Memory figures shown on Docker with Ubuntu 22.04

### ISSUE THREAD

**Issue by flyingnobita** [nicolargo/glances#2112]
**Describe the bug**
Was working fine on Docker with Ubuntu Budgie 20.04 and problem occurs after upgraded to Ubuntu 22.04.

Now the "MEM" shows wrong figures.
```
Column - Glances -  Actual (from System Monitor)
MEM - 72.5% - 51.7%
total - 1.86G - 8.3G
used - 1.4G - 4.3G
free - 529M - 4.0G
```

**To Reproduce**
1. Add glances to Docker Compose file
2. Start Docker and App

**Expected behavior**
The reported memory figures should reflect what's seen in System Monitor.

**Screenshots**
Glances
![image](https://user-images.githubusercontent.com/46126470/185862938-4697c6dc-a3c6-4a61-a506-ddd75c3f714a.png)

System Monitor
![image](https://user-images.githubusercontent.com/46126470/185865465-560d1a7e-2366-4e6c-be26-45cb118c2614.png)

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu 22.04
 - Glances Version: tried on both nicolargo/glances:latest-alpine and nicolargo/glances:latest but with the same result
 - Glances logs file: None shown from docker
 - Glances test [output of glances --issue]: not sure how to do this with docker

**Additional context**

Docker Compose file:
```
  glances:
    image: nicolargo/glances:latest-alpine
    container_name: glances
    restart: unless-stopped
    pid: host
    ports:
      - 61208-61209:61208-61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker_apps/glances/glances.conf:/glances/conf/glances.conf
      - /media:/media:ro
    environment:
      - GLANCES_OPT="-w"
```

glances.conf

```
[fs]
allow=zfs,misc,afpfs,autofs,cifs
```
