### ISSUE TITLE
Docker sort in Web UI fall back to Name

### ISSUE THREAD

**Issue by Cajuteq** [nicolargo/glances#2138]
**Describe the bug**
I launched Glances using Docker compose and Traefik directly inspired by the doc example :

```
version: '2.1'

networks:
  prod:
    external: true

services:
  glances:
    image: nicolargo/glances:latest-alpine
    restart: unless-stopped
    container_name: glances
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w -1"
    labels:
      traefik.enable: true
      traefik.http.routers.glances.entrypoints: websecure
      traefik.http.routers.glances.rule: "Host(`glances.${DOMAIN_NAME}`)"
      traefik.http.services.prometheus.loadbalancer.server.port: 61208
      traefik.http.routers.prometheus.tls.certresolver: myresolver
      org.label-schema.group: "monitoring"
```

my traefik is configured elsewhere and works well for 80+ docker containers, so I safely assume it ain't concerned

**To Reproduce**
1. Start Glances (via docker-compose above) with the followings options '-w -1'
2. Go to glances.${DOMAIN_NAME} in a web browser
3. See that Containers are ordered by name instead of cpu/mem 

**Expected behavior**
I would expect the containers to be sorted by a meaningful sort.

It also seems to happen a mem sort once in a while for a 1 sec duration

**Screenshots**
Name ordered Containers in the web UI
![image](https://user-images.githubusercontent.com/26676532/192790395-e93972d5-3cf2-4010-ad16-66214ef636c5.png)

Once in a while mem sorted containers
![image](https://user-images.githubusercontent.com/26676532/192792231-95225afe-967a-4ef3-b65a-a2e5a8a0159a.png)

**Desktop (please complete the following information):**
 - OS: Debian 10 with Docker 20.10.11 build dea9396
 - Glances Version V3.1.7_beta with PsUtil v5.8.0
 - Glances logs file `Glances Web User Interface started on http://0.0.0.0:61208/`
 - Glances test run without -w
![image](https://user-images.githubusercontent.com/26676532/192791504-768c2cee-8cc0-4e1e-97af-f0b2e2c97265.png)
 - Glances test run with -w
![image](https://user-images.githubusercontent.com/26676532/192791661-cffd8830-75c6-4999-8f3f-b73f5a112a2b.png)

**Additional context**
I did some tests using `docker attach glances` to try to give keyboard input in webUI but that doen't seem to work well, maybe it is related to the once in while mem sort I experience !?
