### ISSUE TITLE
Add a new exporter to MongoDB time-serie

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2203]
Information for implementation:

- MongoDB time serie: https://www.mongodb.com/docs/manual/core/timeseries-collections/
- Python lib: https://pypi.org/project/pymongo/
- https://hub.docker.com/_/mongo

Docker-compose example for test bed:

```
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
```
