### ISSUE TITLE
Improve documentation about the [ip] plugin

### ISSUE THREAD

**Issue by arsaboo** [nicolargo/glances#2251]
**Describe the bug**
I am trying to monitor the public IP address of a server and using Glances to do that. Here's the docker-compose that I use to run Glances:
```
version: "3.5"
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=America/New_York
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/docker/glances:/glances/conf
```
I can monitor the public IP address at the URL - http://192.168.2.78:61208/api/3/ip/public_address

However, the IP address there does not update even if the public IP address changes. A restart updates the IP. 

I have confirmed that `dig +short myip.opendns.com @resolver1.opendns.com` command shows the updated IP address, so the bug is in Glances. 

**Expected behavior**
The public IP address should refresh continuously (or at a pre-defined interval). 

Is there anything that can be done?
