### ISSUE TITLE
Is there anyway that I can use PathPrefix with Traefik?

### ISSUE THREAD

**Issue by chuong98** [nicolargo/glances#2436]
@nicolargo Is there anyway that I can use PathPrefix with Traefik, for example:
This is my docker compose:
```
  server-monitor:
    image: nicolargo/glances:3.3.0.2-full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/glances.conf:/etc/glances.conf
    environment:
      - "GLANCES_OPT=-w -C /etc/glances.conf"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility
    deploy:
      labels:
        - traefik.enable=true
        # router
        - traefik.http.routers.server-monitor.rule=PathPrefix(`/server-monitor`)
        - traefik.http.routers.server-monitor.entrypoints=web
        #service
        - traefik.http.services.server-monitor.loadbalancer.server.port=61208
```

_Originally posted by @chuong98 in https://github.com/nicolargo/glances/issues/1334#issuecomment-1569143737_

**Comment by azhezzzz** [comment]
As Glances does not support the internal configuration of BASE_URL, your BASE_URL is set by an external tool like Traefik. When configuring Traefik, you need to use the middleware feature to remove the corresponding BASE_URL when passing the request. We can achieve this using the stripprefix middleware. 
Additionally, Glances does not use BASE_URL to send requests in the web, so you should match the requests from web with the `HeadersRegexp`. You can try the following use case.
```
version: "3.8"
services:
  traefik:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.9
    ports:
      #   # The HTTP port
      - "80:80"
      #   # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro

  glances:
      container_name: glances
      image: nicolargo/glances:latest
      ports:
        - 61208:61208
      environment:
        GLANCES_OPT: "-w"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      pid: host
      labels:
        - traefik.enable=true
        # Create router name `glances`
        - traefik.http.routers.glances.entrypoints=web
        - traefik.http.routers.glances.rule=PathPrefix(`/server-monitor`) || HeadersRegexp(`Referer`, `.*/server-monitor`)
        # Create a middleware named `glances_stripprefix`
        - traefik.http.middlewares.glances_stripprefix.stripprefix.prefixes=/server-monitor
        # Apply the middleware named `glances_stripprefix` to the router named `glances`
        - traefik.http.routers.glances.middlewares=glances_stripprefix@docker

```
and then you can open `http://127.0.0.1/server-monitor`
