### ISSUE TITLE
Glances Web Unresponsive

### ISSUE THREAD

**Issue by bignay2000** [nicolargo/glances#2453]
Glance Web UI periodically exceeds 48 seconds load time. 

Run Glances 3.4.0.3 in Docker.

Glances Web loads in under 48 seconds load time.  Trying to load from different computers it just hangs.  Then it all the sudden starts working after multiple attempts.
If I restart the container then it works quickly.

I monitor websites with Uptime Kuma (https://github.com/louislam/uptime-kuma)
![Glances_Uptime](https://github.com/nicolargo/glances/assets/11713022/3f5079c2-afea-42d5-afbb-69724c2ccb51)

**Environement (please complete the following information)**
Alpine Linux 3.18.0 64bit on a Linux (From container)
Docker version 20.10.23, build 8659133e59
Linux 5.15.111-flatcar Virtual machine
ESXi-7.0U3m-21686933-standard
HP Z440 Workstation

docker-compose.yml
 ```
 version: '3'
services:
  hiveglance:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    image: nexus.hivetechnologies.net:5000/hiveglance:3.4.0.3
    hostname: glance.hivetechnologies.net
    environment:
      GLANCES_OPT: "-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    ports:
      - "10.10.11.140:80:61208"
      - "10.10.11.140:61209:61209"
    pid: "host"
 ```
Docker Logs
```
Glances Web User Interface started on http://0.0.0.0:61208/
```
