### ISSUE TITLE
Alert timestamp is incorrect

### ISSUE THREAD

**Issue by hoangtran355** [nicolargo/glances#2591]
**Describe the bug**
The timestamp in the "Warning or critical alerts" is in UTC time zone when running in docker-compose with configured TZ variables

**To Reproduce**
1. Start Glances with the following options: Please see my docker-compose configuration below:

```
# Monitoring stats
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    restart: always
    networks:
      - my_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the below line if you want glances to display host OS detail instead>      - /etc/os-release:/etc/os-release:ro
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - GLANCES_OPT=-w
      - TZ=$TZ
    ports:
      - 61208-61209:61208-61209
```

3. Start with `docker compose up -d`
4. Access the container with ` docker exec -it CONTAINER_ID /bin/sh`
5. Verify the time in the container with command `date`
6. The time in the container is changed correctly. 
7. However the timestamp in the "Warning or critical alerts" is still showing UTC time.

**Expected behavior**
The timestamp in "Warning or critical alerts" should be changed accordingly to match the container time.

**Screenshots**
Please see screenshot below:
![image](https://github.com/nicolargo/glances/assets/16659039/4d032f2e-ecdb-42af-9c89-934897750fe8)

**Environement (please complete the following information)**
 - Operating System: Linux raspberrypi 6.1.36-v8+ #1659 SMP PREEMPT Fri Jun 30 13:19:42 BST 2023 aarch64 GNU/Linux

**Additional context**
All configuration is the default. Just set up docker-compose and run.
