### ISSUE TITLE
The log is spammed with appamor denied messages

### ISSUE THREAD

**Issue by janusn** [nicolargo/glances#2607]
**Describe the bug**
I have recently switch to [Journald logging driver](https://docs.docker.com/config/containers/logging/journald/). And I noticed the glances container spams the log with appamor denied messages.

**To Reproduce**
1. Change the log driver of docker to Journald with the following lines added to `/etc/docker/daemon.json`
```
{
  "log-driver": "journald"
}
```
2. restart dockerd
3. Start Glances with the following options '-C /etc/glances.conf -w --password -u ha'
4. Browse the log with the command `$ journalctl -n 1000`
5. See error

**Expected behavior**
There should not be errors related to the container glances.

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `To be completed with result of: lsb_release -a`
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```
 - Glances & psutil versions: `To be completed with result of: glances -V`
```
# glances -V
Glances v3.4.0.3 with PsUtil v5.9.5
Log file: /tmp/glances-root.log
```
 - How do you install Glances (Pypi package, script, package manager, source): `To be completed`
 glances is installed from a docker container on image 'nicolargo/glances:latest-full'
 - Glances test (only available with Glances 3.1.7 or higher):
[pastebin](https://pastebin.com/S6rxPsuT)

**Additional context**
You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
[pastebin](https://pastebin.com/h1AFGx87)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)
Please note for the following log, the PID of the python3 running glances is 1744.
[pastebin](https://pastebin.com/miiPZD0Q)

**Comment by nicolargo** [comment]
Could you please join the log ?

**Comment by janusn** [comment]
> Could you please join the log ?

Sorry, I am not very familiar with the term. What does "join the log" mean?

Btw, I have attached the output of `sudo journalctl -b -g "pid=1744"` for your reference and 
```
[Uploading 1744.log…]()
```

**Comment by nicolargo** [comment]
Add the following option to docker run: **--security-opt seccomp:unconfined**

It should remove the apparmor message.

**Comment by nicolargo** [comment]
Under the hood we need to investigate and understand why Glances needs ptrace access on the system (PsUtil ? another lib ?).

**Comment by janusn** [comment]
> _Workaround_: Add the following option to docker run: **--security-opt seccomp:unconfined**. It should remove the apparmor message.

I have added the option in a compose.yaml but it doesn't help. The warnings are still reported multiple times a second.
```
---
version: "3"
services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    
    # temporary fix for silence the kernel warnings reported by journalctl
    security_opt:
      - seccomp:unconfined

    deploy:
      resources:
        limits:
          memory: 1G
    pid: host
    network_mode: host
    environment:
      - "GLANCES_OPT=-w --password -u ha"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/glances.conf:/etc/glances.conf:ro
#    ports:
#      - 61208:61208
    secrets:
      - source: glances_password
        target: /root/.config/glances/ha.pwd
    restart: unless-stopped
secrets:
  glances_password:
    file: ./secrets/ha.pwd
```

**Comment by nicolargo** [comment]
Strange, it makes the job on my side...

Try to add another option (traditionally to the option **--security-opt seccomp:unconfined**): **–-cap-add=SYS_PTRACE**

If it did not work, replace the previous options with: **--privileged** (ugly work around because it give all the system privileges to the container). You can also have a look on the following post (https://stackoverflow.com/questions/63162665/docker-compose-order-of-cap-drop-and-cap-add/63219871#63219871), it should be possible to limit the **--privileged** option. 

Keep us inform if you find a better solution, nothing is possible from the Glances code.

**Comment by janusn** [comment]
I have tried to replicate your configuration. I have tried 3 tags. And they all spam the log.

Here is my compose.yaml.
```
---
version: "3"
services:
  glances:
    image: nicolargo/glances:latest-full
#    image: nicolargo/glances:alpine-latest
#    image: nicolargo/glances:latest
    container_name: glances-temp
    pid: host
    network_mode: host
    environment:
      "GLANCES_OPT": "--disable-plugin all --enable-plugin processcount,processlist"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```
