### ISSUE TITLE
API is not compatible with requests containing spcial/encoding char

### ISSUE THREAD

**Issue by Smosia** [nicolargo/glances#2820]
**Describe the bug**
When I am trying to get info about mnt_point through API, an empty json is returned.

**To Reproduce**
1. curl http://localhost:61208/api/4/fs/mnt_point
Return:
```
{
  "mnt_point": [
    "/NAS",
    "/etc/resolv.conf",
    "/etc/hostname",
    "/etc/hosts"
  ]
}
```
2. curl http://localhost:61208/api/4/fs/mnt_point/NAS
```
Return:
{
  "NAS": []
}
```
**Expected behavior**
As written in [docs](https://glances.readthedocs.io/en/latest/api.html#get-fs):
```
# curl http://localhost:61208/api/3/fs/mnt_point//
{"/": [{"device_name": "/dev/mapper/ubuntu--gnome--vg-root",
        "free": 4763168768,
        "fs_type": "ext4",
        "key": "mnt_point",
        "mnt_point": "/",
        "percent": 97.9,
        "size": 243334156288,
        "used": 226183532544}]}
```

**Environement (please complete the following information)**
 - Operating System Debian GNU/Linux 12 (bookworm)
 - Glances version: 4.0.7
 - How do you install Glances: docker container through compose file
```
version: '3'
services:
  monitoring:
    image: nicolargo/glances:latest-full
    pid: host
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
      - /media/NAS:/NAS:ro
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208-61209:61208-61209"
```
