### ISSUE TITLE
Sensors plugin generates a peak of CPU consumption

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#2851]
1) Run Glances with the sensor plugin enabled: every 4 refresh a peak of Glances process CPU is observed.
2) Run Glances with the sensor plugin disabled: no CPU peak observed.

**Comment by nicolargo** [comment]
A specific branch (issue2851) has been created with a specific test script (test-data/issues/issue2851.py):

```
./venv/bin/python ./test-data/issues/issue2851.py 
True
1/6
2/6
3/6
4/6
5/6
6/6
CPU consumption with sensors plugin enable: 11.6
False
1/6
2/6
3/6
4/6
5/6
6/6
CPU consumption with sensors plugin disable: 5.8
 ```

**Comment by nicolargo** [comment]
After a quick analyse, the peak came from the calls to [psutil.sensors_temperatures() and psutil.sensors_fans()](https://psutil.readthedocs.io/en/latest/#sensors).

**Comment by eric72777** [comment]
I don't know if it's related to this issue, but I noticed significantly higher CPU usage on recent versions of glances.

I've noticed this on multiple machines, but it's currently running on Docker version 25.0.6. 

Old version with good CPU usage:

```
  glances:
    container_name: glances
    environment:
      - GLANCES_OPT=-w --disable-check-update --time 2 --disable-plugin amps,containers,processcount
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    network_mode: host
    image: docker.io/nicolargo/glances:3.4.0.5-full
    restart: unless-stopped
```

Newer version with high CPU usage:

```
  glances:
    container_name: glances
    environment:
      - GLANCES_OPT=-w --disable-check-update --time 2 --disable-plugin amps,containers,processcount
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    network_mode: host
    image: docker.io/nicolargo/glances:latest #4.1.2.1
    restart: unless-stopped
```
