### ISSUE TITLE
Timezone for warning/errors is incorrect

### ISSUE THREAD

**Issue by leddie24** [nicolargo/glances#2901]
**Check the bug**
Before filling this bug report, please search if a similar issue already exists.
In this case, just add a comment on this existing issue.

**Describe the bug**

![image](https://github.com/user-attachments/assets/ed5419f9-d555-4920-b4d4-2a20b34f90e8)

Current time of posting this is 3:39 PM.

**To Reproduce**
1. Start Glances with the following options '...'
2. Press the key '....'
3. See error

Docker compose file
```
services:
  monitoring:
    image: nicolargo/glances:latest
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "GLANCES_OPT=-w"
      - TZ=America/Los_Angeles

```

**Expected behavior**

**Screenshots**

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): `To be completed with result of: lsb_release -a`
 - Glances & psutil versions: `To be completed with result of: glances -V`
 - How do you install Glances (Pypi package, script, package manager, source): `To be completed`
 - Glances test: ` To be completed with result of: glances --issue`

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)
