### ISSUE TITLE
url_prefix do not work in Glances < 4.2.0

### ISSUE THREAD

**Issue by v-bulynkin** [nicolargo/glances#2912]
Hello!
I have a docker-compose installation of several services which are published on various prefixes - /cloud, /wiki and so on.
I have seen the [reverse proxy examples](https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI), there are redirects from "/glances" to "/". But at "/" I already have a service and I ended up with 404 error.

Is it possible to change webroot in a Glances docker container? For example, it would be great to have an environment variable like

```yaml
  environment:
    WEBROOT: /glances
```
And after that, Glances would respond at http://site:61208/glances

I use Traefik as reverse proxy and I tried the following but no luck:
```yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.routers.glances.rule=Host(`example.com`) && PathPrefix(`/glances`)"
      - "traefik.http.routers.glances.middlewares=glances-strip"
      - "traefik.http.middlewares.glances-strip.stripprefix.prefixes=/glances"
      - "traefik.http.routers.glances.tls.certresolver=le"
      - "traefik.http.routers.glances.entrypoints=websecure"
```

**Comment by nicolargo** [comment]
Hi @v-bulynkin 

my assumption is that you use the latest Docker image.

You can configure the url_prefix from the glances.conf file: https://github.com/nicolargo/glances/blob/v4.1.2.1/conf/glances.conf#L40

Can you try this ?

**Comment by v-bulynkin** [comment]
Thank you for the response!
Yes, I am using the latest image. I tried url_prefix, but it doesn't work. I disabled reverse-proxy for Glances and I am trying directly now.
I made the following:
1. `docker cp glances:/etc/glances/glances.conf ./glances/glances.conf` and uncommented `url_prefix=/glances/`
2. Edited docker-compose.yml and mounted the config file from the host to container:
```yaml
  glances:
    image: nicolargo/glances
    container_name: glances
    restart: unless-stopped
    pid: host
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - ./glances/glances.conf:/etc/glances/glances.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.glances.loadbalancer.server.port=61208"
#      - "traefik.http.routers.glances.rule=Host(`example.com`) && PathPrefix(`/glances/`)"
#      - "traefik.http.routers.glances.tls.certresolver=le"
#      - "traefik.http.routers.glances.entrypoints=websecure"
    ports:
      - 61208:61208
```
3. docker compose restart glances

Container works, but when I try to open http://<local host ip>:61208/glances/, I get a JSON
```json
{"detail":"Not Found"}
```
When I open http://<local host ip>:61208, it works.
