### ISSUE TITLE
Cannot run on ARM ?

### ISSUE THREAD

**Issue by signmeuptwice** [nicolargo/glances#2988]
Trying to run the docker version on my raspberry pi

on my mac it runs fine but on raspberry pi I get error with `docker logs` the container keeps restarting:

```
docker logs glances
exec /bin/sh: exec format error
```

here is my `docker-compose`. I also tried the ubuntu version

```
  monitoring:
    container_name: glances
    image: nicolargo/glances:latest
    restart: always
    pid: host
    ports:
      - "61208:61208"
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"
```
