### ISSUE TITLE
Allow Setting-up docker container hostname via environment variable

### ISSUE THREAD

**Issue by jo-chemla** [nicolargo/glances#3122]
**Is your feature request related to a problem? Please describe.**
Context is mentioned [here](https://github.com/portainer/portainer/issues/12546#issuecomment-2690332793), I'm using portainer edge stacks to deploy a `glances agent` on a list of servers. Portainer does not pass its own container hostname to the containers created from the stack. Passing the `HOSTNAME` environment variable from a `env_file: .env ` in the compose stack, or mapping the `/etc/hostname:/etc/hostname:ro` is not sufficent enough, since running the `hostname` command on the container will show a hostname different from both values. 

**Describe the solution you'd like**
It would be nice if hostname could be passed to the docker container as an environment variable. This way it would be possible to have an explicit name that is dependent on the real host hostname, rather than a manually set value. Manually setting that value is indeed impossible for agents deployed as portainer stacks. 

**Describe alternatives you've considered**
Using one `.env` per host is probably the solution, but docker-compose doees not populate environment variables like `hostname: ${CUSTOM_HOSTNAME}`

Also, it is possible using such endpoint could potentially work, but at the moment I'm faced with error: `hostname: sethostname: Operation not permitted`. Or `cap_add: - SYS_ADMIN` but would give root access to host. 

```yaml
    volumes:
      # ...
      - /etc/hostname:/etc/hostname:ro
    entrypoint: ['/bin/sh', '-c', 'echo "setting hostname" && hostname -F /etc/hostname && hostname && python -m glances -C /glances/conf/glances.conf $GLANCES_OPT']

```
