### ISSUE TITLE
LDCache Error When Specifying NVIDIA GPU

### ISSUE THREAD

**Issue by royaltongue** [nicolargo/glances#3144]
**Check the bug**
~~Before filling this bug report, please search if a similar issue already exists.~~
~~In this case, just add a comment on this existing issue.~~

**Describe the bug**
Cannot create container with NVIDIA GPU. Error:
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: ldcache error: process /sbin/ldconfig failed with error code: 2: unknown`

**To Reproduce**
1. Create a `docker-compose.yml`
2. Specify
```
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
3. Try to start container

**Expected behavior**

Container should start normally

**Screenshots**
N/A

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): 
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```
 - Glances & psutil versions: Latest
 - How do you install Glances (Pypi package, script, package manager, source): Docker
 - Glances test: N/A

**Additional context**
`docker-compose.yml`
```
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GLANCES_OPT: -w
    network_mode: host
    restart: unless-stopped
```

* the Glances configuration file: N/A
* the Glances log file: N/A
