### ISSUE TITLE
Crash on startup with KeyError: 'getpwuid(): uid not found

### ISSUE THREAD

**Issue by Neurrone** [nicolargo/glances#3207]
**Check the bug**
Before filling this bug report, please search if a similar issue already exists.
In this case, just add a comment on this existing issue.

**Describe the bug**

When I try to run Glances via docker compose, it crashes.

**To Reproduce**
use the following docker compose file

```yaml
services:
  glances:
    image: nicolargo/glances:4.3.1
    container_name: glances
    environment:
      - GLANCES_OPT="-w"
      - TZ=Asia/Singapore
    networks:
      - glances
    pid: host
    restart: unless-stopped
    ports:
      - "61208:61208"
      - "61209:61209"
    volumes:
      - ./data/glances.conf:/etc/glances/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro

networks:
  glances:
```

Start it with `docker compose up`

**Expected behavior**

Glances should start.

**Screenshots**

```sh
> docker compose up
[+] Running 2/2
 ✔ Network glances_glances  Created                                                                                                                    0.0s
 ✔ Container glances        Created                                                                                                                    0.0s
Attaching to glances
glances  | Traceback (most recent call last):
glances  |   File "<frozen runpy>", line 189, in _run_module_as_main
glances  |   File "<frozen runpy>", line 148, in _get_module_details
glances  |   File "<frozen runpy>", line 112, in _get_module_details
glances  |   File "/app/glances/__init__.py", line 36, in <module>
glances  |     from glances.logger import logger
glances  |   File "/app/glances/logger.py", line 38, in <module>
glances  |     LOG_FILENAME = os.path.join(tempfile.gettempdir(), f'glances-{getpass.getuser()}.log')
glances  |                                                                   ^^^^^^^^^^^^^^^^^
glances  |   File "/usr/lib/python3.12/getpass.py", line 169, in getuser
glances  |     return pwd.getpwuid(os.getuid())[0]
glances  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
glances  | KeyError: 'getpwuid(): uid not found: 1000'
glances exited with code 0
```

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): debian bookworm 12
 - Glances & psutil versions: 4.3.1
 - How do you install Glances (Pypi package, script, package manager, source): Docker
 - Glances test: couldn't get to this stage

**Additional context**

You can also [pastebin](https://pastebin.com/):

* the Glances configuration file (https://glances.readthedocs.io/en/latest/config.html#location)
* the Glances log file (https://glances.readthedocs.io/en/latest/config.html#logging)
