### ISSUE TITLE
Add a Prometheus export module

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#930]
#### Description

Prometheus server scrapes and stores time series data.
The goal is to add an export module for this NoSQL DB.
#### Sources

Main site: https://prometheus.io/docs/introduction/overview/
Docker container (for testbed): https://hub.docker.com/r/prom/prometheus/
Python API: https://github.com/prometheus/client_python#gauge

**Testbed**

Running Prometheus on Docker is as simple as:

    docker run --net="host" -v ~/tmp/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

This starts Prometheus with a sample configuration and exposes it on port 9090.

On your host, the Glances Prometheus plugin will create a Prometheus exporter running on default TCP port 9091. The Prometheus server will collect the Glances stats from the exporter thanks to the following configuration (in the ~/tmp/prometheus.yml file):

```
scrape_configs:
  - job_name: 'glances_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9091']
```
