### ISSUE TITLE
Type Error when export to influxdb

### ISSUE THREAD

**Issue by nangong** [nicolargo/glances#970]
I am exporting glances into infludb, but the following error happens and meanwhile glances crashed:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/glances/glances/plugins/glances_ports.py", line 173, in run
    self._port_scan(p)
  File "/glances/glances/plugins/glances_ports.py", line 201, in _port_scan
    if int(port['port']) == 0:
TypeError: string indices must be integers, not str
```

Both of my glances service and influxdb service are managed by docker , here is my docker-compose.yml:

```
version: "2"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - "influxdb"
  glances:
    image: "nicolargo/glances"
    #tty: true
    # stdin_open: true
    environment:
     - "GLANCES_OPT=--export-influxdb -q"
    # entrypoint: /bin/bash
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf:/glances/conf"
    depends_on:
      - "influxdb"
    pid: "host"
  influxdb:
    image: tutum/influxdb:latest
    environment:
      - "ADMIN_USER=root"
      - "INFLUXDB_INIT_PWD=root"
      - "PRE_CREATE_DB=glances"
    volumes:
      - "./influx:/data"
    ports:
      - "8086:8086"
      - "8083:8083"
    expose:
      - "8090"
      - "8099"
```

I print several logs in glances_ports.py, and I found the code in the method "_port_scan" ,
```
    def _port_scan(self, port):
        """Scan the port structure (dict) and update the status key"""
        logger.error("ports may contains error -{}".format(port))
        if int(port['port']) == 0:
            return self._port_scan_icmp(port)
        else:
            return self._port_scan_tcp(port)
```
 in which the logger print the following message:

```
2016-11-23 12:58:30,135 -- ERROR -- ports may error -{'status': None, 'description': 'DefaultGateway', 'refresh': 30, 'host': '172.118.0.1', 'rtt_warning': None, 'timeout': 3, 'port': 0}
2016-11-23 12:58:31,298 -- ERROR -- ports may error -history_size
```
the first line shows the argument "port" is a dict but the second line the argument "port" is a string.
